# Generated by Django 3.2.12 on 2024-06-06 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentification', '0003_remove_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnseignantModels',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentification.customuser')),
                ('specialite', models.CharField(max_length=100, verbose_name='Specialite')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
            bases=('Authentification.customuser',),
        ),
    ]
