# Generated by Django 3.2.12 on 2024-06-07 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentification', '0004_customuser_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantModels',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentification.customuser')),
                ('etudiant_filiere', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Filière')),
                ('etudiant_niveau', models.CharField(blank=True, default=None, max_length=5, null=True, verbose_name='Niveau')),
                ('etudiant_promotion', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Promotion')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
            bases=('Authentification.customuser',),
        ),
    ]
