# Generated by Django 3.2.12 on 2024-07-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0002_studentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='module',
            field=models.CharField(default='', max_length=100, verbose_name='Module'),
        ),
    ]
