# Generated by Django 3.2.12 on 2024-07-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiant', '0003_studentfile_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='fichier',
            field=models.FileField(max_length=255, upload_to='student_files/'),
        ),
    ]
