# Generated by Django 3.2.12 on 2024-06-21 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentification', '0001_initial'),
        ('Enseignant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScolariteModels',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentification.customuser')),
                ('fonction', models.CharField(max_length=100, verbose_name='Emploi/Fonction')),
                ('etablissement', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scolarite_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scolarite',
                'verbose_name_plural': 'Scolarites',
            },
            bases=('Authentification.customuser',),
        ),
        migrations.CreateModel(
            name='DossierImageTif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant_nom', models.CharField(default='', max_length=100)),
                ('enseignant_prenom', models.CharField(default='', max_length=100)),
                ('module', models.CharField(default='', max_length=100, verbose_name='Module')),
                ('promotion', models.CharField(default='', max_length=100, verbose_name='Promotion')),
                ('niveau', models.CharField(default='', max_length=100, verbose_name='Niveau')),
                ('nombre', models.IntegerField(default='', verbose_name='Nombre de copies')),
                ('dossier', models.FileField(upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Enseignant.enseignantmodels')),
                ('scolarite', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ScolaritePersonal.scolaritemodels')),
            ],
        ),
    ]
