# Generated by Django 3.2.12 on 2024-06-23 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScolaritePersonal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierimagetif',
            name='scolarite',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ScolaritePersonal.scolaritemodels'),
        ),
    ]
