# Generated by Django 3.2.12 on 2024-06-23 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScolaritePersonal', '0002_alter_dossierimagetif_scolarite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierimagetif',
            name='scolarite',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ScolaritePersonal.scolaritemodels'),
        ),
    ]
