# Generated by Django 3.2.12 on 2024-06-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScolaritePersonal', '0002_dossier_imagetif'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierImageTif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.FileField(upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='dossier_imageTif',
        ),
    ]
