# Generated by Django 3.2.12 on 2024-06-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScolaritePersonal', '0003_alter_dossierimagetif_scolarite'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierimagetif',
            name='ufr',
            field=models.CharField(default='', max_length=100, verbose_name='UFR'),
        ),
    ]
