# Generated by Django 3.2.12 on 2024-06-16 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enseignant', '0001_initial'),
        ('ScolaritePersonal', '0003_auto_20240616_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierimagetif',
            name='enseignant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Enseignant.enseignantmodels'),
        ),
    ]
