# Generated by Django 3.2.12 on 2024-06-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScolaritePersonal', '0004_dossierimagetif_ufr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossierimagetif',
            name='ufr',
        ),
    ]
