# Generated by Django 3.2.12 on 2024-06-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScolaritePersonal', '0004_dossierimagetif_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierimagetif',
            name='module',
            field=models.CharField(default='', max_length=100, verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='dossierimagetif',
            name='niveau',
            field=models.CharField(default=0, max_length=100, verbose_name='Niveau'),
        ),
        migrations.AddField(
            model_name='dossierimagetif',
            name='nombre',
            field=models.IntegerField(default=0, verbose_name='Nombre de copies'),
        ),
        migrations.AddField(
            model_name='dossierimagetif',
            name='promotion',
            field=models.CharField(default=0, max_length=100, verbose_name='Promotion'),
        ),
    ]
