# Generated by Django 3.2.12 on 2024-06-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScolaritePersonal', '0005_auto_20240619_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierimagetif',
            name='nombre',
            field=models.IntegerField(default='', verbose_name='Nombre de copies'),
        ),
        migrations.AlterField(
            model_name='dossierimagetif',
            name='promotion',
            field=models.CharField(default='', max_length=100, verbose_name='Promotion'),
        ),
    ]
