# Generated by Django 3.2.12 on 2024-06-30 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enseignant', '0001_initial'),
        ('ScolaritePersonal', '0005_remove_dossierimagetif_ufr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossierimagetif',
            name='enseignant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Enseignant.enseignantmodels'),
        ),
    ]
