# Generated by Django 3.2.12 on 2024-06-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScolaritePersonal', '0006_auto_20240619_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierimagetif',
            name='enseignant_nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dossierimagetif',
            name='enseignant_prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dossierimagetif',
            name='niveau',
            field=models.CharField(default='', max_length=100, verbose_name='Niveau'),
        ),
    ]
