# Generated by Django 3.2.12 on 2024-05-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('scolarite', 'Scolarite'), ('enseignant', 'Enseignant')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
