# Generated by Django 3.2.12 on 2024-05-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matricule',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, verbose_name='Matricule'),
        ),
    ]
