# Generated by Django 3.2.12 on 2024-06-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0002_auto_20240526_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
