# Generated by Django 3.2.12 on 2024-05-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0002_alter_customuser_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
