# Generated by Django 3.2.12 on 2024-06-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0003_remove_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Etudiant'), ('scolarite', 'Scolarite'), ('enseignant', 'Enseignant')], default='student', max_length=20),
        ),
    ]
