# Generated by Django 3.2.12 on 2024-06-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0004_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Etudiant'), ('scolarite', 'Scolarite'), ('enseignant', 'Enseignant')], default='', max_length=20),
        ),
    ]
