# Generated by Django 3.2.12 on 2024-05-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0004_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
