# Generated by Django 3.2.12 on 2024-04-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPrincipale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scolarite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
        migrations.DeleteModel(
            name='Scolarite',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
