# Generated by Django 3.2.12 on 2024-05-14 00:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPrincipale', '0004_auto_20240512_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scolaritemodels',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='scolaritemodels',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='scolaritemodels',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scolaritemodels',
            name='user',
        ),
        migrations.AddField(
            model_name='scolaritemodels',
            name='customuser_ptr',
            field=models.OneToOneField(default='default', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scolaritemodels',
            name='fonction',
            field=models.CharField(max_length=100, verbose_name='Emploi/Fonction'),
        ),
    ]
