# Generated by Django 3.2.12 on 2024-05-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPrincipale', '0005_auto_20240514_0014'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='scolaritemodels',
            managers=[
            ],
        ),
    ]
