# Generated by Django 3.2.12 on 2024-05-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0005_alter_customuser_managers'),
        ('UserPrincipale', '0006_alter_scolaritemodels_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnseignantModels',
            fields=[
                ('specialite', models.CharField(max_length=100, verbose_name='Specialite')),
                ('customuser_ptr', models.OneToOneField(default='default', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Authentification.customuser')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Authentification.customuser',),
        ),
    ]
